# Generated by Django 6.0.6 on 2026-06-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActaElectoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_acta', models.CharField(max_length=50, unique=True)),
                ('canton', models.CharField(max_length=100)),
                ('parroquia', models.CharField(max_length=100)),
                ('zona', models.CharField(max_length=100)),
                ('junta', models.CharField(max_length=10)),
                ('empadronados', models.IntegerField()),
                ('votos_validos', models.IntegerField()),
                ('votos_blancos', models.IntegerField()),
                ('votos_nulos', models.IntegerField()),
                ('hora_ingreso', models.DateTimeField()),
                ('es_anomala', models.BooleanField(default=False, null=True)),
                ('porcentaje_riesgo', models.FloatField(default=0.0, null=True)),
            ],
        ),
    ]
