# Generated by Django 6.0.6 on 2026-07-05 23:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actaelectoral',
            name='anio_eleccion',
            field=models.IntegerField(default=2025, help_text='Año del proceso electoral (ej. 2016, 2021, 2025)'),
        ),
        migrations.AlterField(
            model_name='actaelectoral',
            name='hora_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
